language: node_js
node_js:
  - "5" # Can't make tests work for higher node versions.
  # - "node" # Would install latest version of node.
sudo: required
env:
  - CXX=g++-4.8
before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
addons:
  apt:
    packages:
    - libfuse-dev
    - fuse
    - g++-4.8